server:
  servlet.context-path: /api/shop
  port: 8001
# max upload file size
spring:
  http:
    multipart:
      max-file-size: 5MB
# swagger ui
springdoc:
  api-docs:
    enabled: true
# Keycloak configuration
keycloak:
  # when using self signed certificate => use a special http vhost to avoid handling java pkix (untrusted root ca)
  auth-server-url: https://cluster.nearmi-dev/auth
  realm: nearmi-dev
  bearerOnly: true
  ssl-required: external
  resource: nearmi-back
  cors: false
  confidential-port: 0

# app configuration (mongo + override security)
nearmi:
  config:
    dbName: 'nearmi-dev'
    dbUsername: 'nearmi-dev'
    dbPassword: 'dev@password'
    cluster: 'cluster0.kvkgz.mongodb.net'
    override-security: true
    max-distance: 10000.0
    debugSecurity: true
    #accepted mime type for images
    acceptedImageMime: image/jpeg, image/png
    dataPath: '/nearmi/data'
    max-image-for-shop: 15
    #list of sub-folders where product image will be stored
    product-image-sub-folders: products