server:
  servlet.context-path: /api
  port: 8001

# Keycloak configuration
keycloak:
  # when using self signed certificate => use a special http vhost to avoid handling java pkix (untrusted root ca)
  auth-server-url: http://keycloak.untrusted.certificate/auth
  realm: nearmi-dev
  bearerOnly: true
  ssl-required: external
  resource: nearmi-back
  cors: false
  confidential-port: 0
# app configuration (mongo + override security)
nearmi:
  config:
    dbName: 'nearmi-dev'
    dbUsername: 'nearmi-dev'
    dbPassword: 'dev@password'
    cluster: 'cluster0.kvkgz.mongodb.net'
    override-security: true
    max-distance: 10000.0
  cors:
    allowedOrigins: 'http://localhost:3000'
    allowedMethods: 'GET, PUT, POST, OPTIONS, HEAD'

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG