server:
  servlet.context-path: /api
  port: 8001
#Max file upload 5mb
spring:
  http:
    multipart:
      max-file-size: 5MB

# Keycloak configuration
keycloak:
  auth-server-url: https://cluster.nearmi-dev/auth
  realm: nearmi-dev
  bearerOnly: true
  ssl-required: external
  resource: nearmi-back
  cors: false
  confidential-port: 0
# app configuration (mongo + override security)
nearmi:
  config:
    dbName: 'nearmi-dev'
    dbUsername: 'nearmi-dev'
    dbPassword: 'dev@password'
    cluster: 'cluster0.kvkgz.mongodb.net'
    override-security: true
    max-distance: 10000.0
    debugSecurity: true
    acceptedImageMime: 'image/jpeg, image/png'
    dataPath: '/nearmi/data'
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG